spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasklist?currentSchema=tasklist
    username: root
    password: rjkzcrfgbljhfcrf
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: cXdvZWhxd2lid2llYmZ3Zmlid2VpZnli
    access: 3600000
    refresh: 2592000000