spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: d2VmYndpdWZiaXdldWJmaXV3ZWJmaXdldWJmaXdldWJmaXdiZXVmYml3dWViZmlld2JmaWViZml3ZWZid2lldWJmaXdldWJmaXc=
    access: 3600000
    refresh: 2592000000

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        boot:
          autoconfigure: DEBUG
